#!/usr/bin/env bash
# Make headless Chromium runnable without sudo.
#
# `playwright install --with-deps` shells out to apt and needs root, which this box
# does not grant without a password (see docs/HANDOFF.md — ffmpeg and uv are installed
# the same way, from static builds into ~/.local). So the shared libraries Chromium
# needs are downloaded as .debs and unpacked into a prefix, and LD_LIBRARY_PATH points
# at them. No root, nothing written outside $HOME.
#
#   bash app/tests/install_browser_deps.sh          # one-off
#   source app/tests/browser_env.sh                 # per shell, before pytest
set -euo pipefail

PREFIX="${PREFIX:-$HOME/.local/chromium-deps}"
mkdir -p "$PREFIX/debs"
cd "$PREFIX/debs"

PKGS=(
  libnspr4 libnss3 libnssutil3 libsmime3
  libatk1.0-0t64 libatk-bridge2.0-0t64 libatspi2.0-0t64
  libcups2t64 libdrm2 libgbm1 libxkbcommon0
  libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libxext6
  libpango-1.0-0 libpangocairo-1.0-0 libcairo2 libasound2t64
)

# Resolved through apt-cache and fetched with curl rather than `apt-get download`,
# which fails quietly for some packages as an unprivileged user. apt still supplies
# the pool path and version, so this stays correct as the archive moves on.
MIRROR="${MIRROR:-http://archive.ubuntu.com/ubuntu}"
echo "downloading ${#PKGS[@]} packages..."
for p in "${PKGS[@]}"; do
  # `|| true`: under `set -o pipefail` a non-zero apt-cache aborts the assignment
  fn=$(apt-cache show "$p" 2>/dev/null | awk '/^Filename:/{print $2; exit}' || true)
  if [ -z "$fn" ]; then echo "  (skip $p — unknown to apt)"; continue; fi
  out=$(basename "$fn")
  # `if`, not `[ -s ] && continue`: under `set -e` a false && list aborts the script
  if [ -s "$out" ]; then echo "  have $p"; continue; fi
  if curl -fsSL "$MIRROR/$fn" -o "$out"; then
    echo "  got  $p"
  elif curl -fsSL "http://security.ubuntu.com/ubuntu/$fn" -o "$out"; then
    echo "  got  $p (security pocket)"
  else
    echo "  FAIL $p"
  fi
done

echo "unpacking..."
for d in *.deb; do
  [ -e "$d" ] || continue
  dpkg-deb -x "$d" "$PREFIX/root"
done

LIBDIR=$(find "$PREFIX/root" -name 'libnspr4.so*' -printf '%h\n' 2>/dev/null | head -1)
cat > "$(dirname "$0")/browser_env.sh" <<EOF
# generated by install_browser_deps.sh — source before running the UI tests
export LD_LIBRARY_PATH="$PREFIX/root/usr/lib/x86_64-linux-gnu:\${LD_LIBRARY_PATH:-}"
EOF

echo "libs in: ${LIBDIR:-<none found>}"
echo "wrote $(dirname "$0")/browser_env.sh"
